### ISSUE TITLE
Running your YM2413 on Cortex M0+ (RP2040)

### ISSUE THREAD

**Issue by jeroentaverne** [FluBBaOfWard/YM2413#1]
Hi. I am impressed about all your emulator projects! I want to try to run your YM2413 on a Raspberry Pi Pico. Would it be possible for you to make a version that uses ARM thumb instructions? I have no clue about ARM assembly code myself. This way we would be able to connect a Pi Pico to for instance an old MSX computer and emulate the Fm-Pac cartridge. I would really appreciate it.

**Comment by FluBBaOfWard** [comment]
I don't think there is any reason to make a version in thumb, any compiler is probably better than me at doing that.
Why can't/won't you use ARM asm? Is there only 16-bit memory on the Pi Pico?

**Comment by jeroentaverne** [comment]
Hi,

Thanks for your reply.

Is the compiler able to convert the full instructions to thumb
instructions? The Pico is 32 bits but only able to run in thumb mode.
Perhaps I need to change the configuration so the conversion takes place?
Currently I only get thumb instruction errors.

Best regards,

Jeroen

**Comment by FluBBaOfWard** [comment]
Apparently you can't run arm32 on the Cortex-M0+, thumb is just to limited to code asm on for me.

**Comment by jeroentaverne** [comment]
Ok. Thanks anyway.
